### ISSUE TITLE
/list default behavior 

### ISSUE THREAD

**Issue by darwinjob** [irods/irods_client_rest_cpp#114]
Hi
I have a folder/collection with over 20000 files. When I list that folder or **any parent folder** it takes several minutes (!) to respond. Why does the list endpoint list all sub folders and their content? Shouldn’t it just list a folder I specify? Also, shouldn’t there be a reasonable default limit like 50 for example?

**Comment by korydraughn** [comment]
I agree with your assessment and we'll look into making things better.

Things to investigate:
- Expose option that allows toggling the use of a recursive collection iterator
- Consider exposing option that limits the number of results
    - The downside to this is the collection iteration APIs do not support offsets
    - To reach the next set of entries, the REST API must iterate through the previous set of entries

**Comment by korydraughn** [comment]
We'll look into the /list endpoint being unresponsive. That is definitely a bug.

As for *offset*, I'm referring to the underlying iRODS Collection APIs (used by the REST API) not providing support for *offset* in the iRODS server.

The offset and limit options are features provided by the REST API. If you have a collection that contains 10,000 items and you want to jump to item 5001, the REST API will simply iterate through 5000 items instead of jumping to the position instantaneously. This is fine, but it isn't optimal.

See the following:
https://github.com/irods/irods_client_rest_cpp/blob/bd5393556f20533e44c338b6f47b95077a12b3c5/irods_specific_implementation/irods_rest_list_api_implementation.h#L75-L79

The implementation of offset means we still pay for construction and memory use of unused collection entries. There are a couple things we can do in the iRODS server to improve this situation, but that is outside the scope of the REST API.

**Comment by darwinjob** [comment]
I see. Thanks :)

**Comment by darwinjob** [comment]
Is there any time estimation?

**Comment by korydraughn** [comment]
We are working on getting iROD 4.3.0 released. It is very close and could happen any day now.

Once that is complete, I can shift focus to this and knock it out.

**Comment by alanking** [comment]
The default behavior of the /list endpoint is now *non*-recursive, so that should help a little bit. It sounds like there may be further investigation to be had with respect to iterating through collection items, so I will leave this open.

Does that seem right, @korydraughn / @trel?

**Comment by korydraughn** [comment]
Yes. Let's give @darwinjob a chance to test the changes out and report back.

**Comment by adilhasan** [comment]
Hello Kory, how can we test it? Do we need to wait for a new release? Many thanks, adil

**Comment by korydraughn** [comment]
You don't have to wait for a release. Compiling from source should be easier thanks to the Docker work completed by @alanking.

See the following sections from the README.
- https://github.com/irods/irods_client_rest_cpp#building-with-docker
- https://github.com/irods/irods_client_rest_cpp#starting-the-services-with-docker-compose

You're going to want to read through the README in case the API has changed (we expect the API to change as we move towards v1.0).

@alanking Do you have any additional advice that may help them in standing this up?

**Comment by alanking** [comment]
The main thing that has changed is the JSON configuration and the location of some of the files. This was done as part of the effort in #66 to separate the client from the server and the iCommands.

The various configuration files moved from `/etc/irods` to `/etc/irods_client_rest_cpp`. Ownership of said files goes to root:root because we no longer assume the existence of an `irods` service account user. Along those lines, the `/etc/init.d` file no longer makes the `irods` service account the owner of the REST services. 

The `irods_client_rest_cpp.json` configuration file now has 2 sections: `irods_client_environment` and `rest_api`. The `rest_api` section is almost identical to the way this file was structured before (configurations for each REST service), but there is now a `jwt_signing_key` in addition to these. The JWT signing key used to be derived from the zone key found in `/etc/irods/server_config.json`.

The `irods_client_environment` must contain the information found in the template file in order to provide server connection and proxy user information. Authenticating as the proxy user still requires that the Linux user issuing the requests has a `~/.irods/` directory into which a `.irodsA` file will be placed for iRODS native authentication.

Finally, the new package is only compatible with `irods-runtime` version 4.3.0. This means that you cannot deploy the client on the same machine as a 4.2.x server via packages because there will be a conflict in the dependencies. That said, as @korydraughn mentioned, standing up the client on a separate host is made pretty trivial with the Docker Compose project under `docker/runner`.

I think that covers all the differences. Let us know if you have any questions or concerns.

**Comment by korydraughn** [comment]
Closing this as the primary issue has been resolved.

@darwinjob @adilhasan If you run into other problems, please open new issues for them.
