### ISSUE TITLE
Unable to locate package irods-client-rest-cpp

### ISSUE THREAD

**Issue by JvD007** [irods/irods_client_rest_cpp#141]
I am trying to install iRODS client rest.api on Ubuntu 20.04.5 LTS, installing iRODS 4.3 worked fine, but when running the following I get an error message

$ **sudo apt install irods-client-rest-cpp**

Read package lists... Done
Build dependencies tree       
Read status information... Done
**E: Can't find package irods-client-rest-cpp**

Any idea and where can I find the package?

**Comment by trel** [comment]
Hi @JvD007 - we've not published packages for this project yet - it's still a moving target.

You'll need to build it yourself at the moment.

We're working hard to make that easier (docker) - maybe even by the end of today(!).

**Comment by trel** [comment]
We did it - please pull the repo, and try the new docker builder.

**Comment by JvD007** [comment]
Hi Terrell,

I'm going to try it out

Thanks
Jaco

**Comment by alanking** [comment]
Turns out, we *have* released packages for this project, but not for Ubuntu 20.04. Historically, the client had to run on the same host as an iRODS server and was compatible with the 4.2.x series. The supported platforms for those servers are Ubuntu 16.04/18.04 and CentOS 7. The released REST C++ client packages will not be compatible with iRODS 4.3.0.
