### ISSUE TITLE
error while build

### ISSUE THREAD

**Issue by peggy0135** [irods/irods_client_rest_cpp#186]
hi @trel @korydraughn ,

I tried to build from source for irods 4.3 on rocky 8.

1. build irods-externals on rocky 8 ------ done
2. build irods-server on rocky 8 --------- done
3. build icommand on rocky 8 ---------- done
4. build irods_client_rest_cpp:
    stuck at In file included from /opt/irods-externals/pistache0.0.2-0/include/pistache/http.h:21
    

> In file included from /opt/irods-externals/pistache0.0.2-0/include/pistache/http.h:21:
> /opt/irods-externals/pistache0.0.2-0/include/pistache/cookie.h:56:26: error: 'iterator<std::bidirectional_iterator_tag, Pistache::Http::Cookie>' is deprecated [-Werror,-Wdeprecated-declarations]
>   struct iterator : std::iterator<std::bidirectional_iterator_tag, Cookie> {
>                          ^
> /opt/irods-externals/clang13.0.0-0/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::bidirectional_iterator_tag, Pistache::Http::Cookie>' has been explicitly marked deprecated here
> struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
>                             ^
> /opt/irods-externals/clang13.0.0-0/include/c++/v1/__config:1016:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
> #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
>                                       ^
> /opt/irods-externals/clang13.0.0-0/include/c++/v1/__config:993:48: note: expanded from macro '_LIBCPP_DEPRECATED'
> #    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
>                                                ^
> 1 error generated.
> make[2]: *** [CMakeFiles/irods_client_rest_cpp_logicalpath_server.dir/build.make:76: CMakeFiles/irods_client_rest_cpp_logicalpath_server.dir/LogicalPathApiMainServer.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/irods_client_rest_cpp_logicalpath_server.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2

also I stuck at the http_api at a similar error with "pistache" 
Is there anything can help to figure out it?
Thank you.

**Comment by korydraughn** [comment]
The formatting of the build output needs to be tweaked. Please adjust the code block so that it is easy to read.

Have you tried compiling the project using the docker images? Can you use docker? That is the easiest way to build/deploy it.

You can try comparing what you have to the docker builder image to see if there are any differences. See https://github.com/irods/irods_client_rest_cpp/tree/45ae4791969f2e09a2fe0c5cd0eb1031773316b2/docker/builder.

> also I stuck at the http_api at a similar error with "pistache"

Are you referring to the new HTTP API that was recently discussed at the conference?

If so, then it has no dependencies on Pistache. However, it cannot be compiled against any released versions of iRODS because it depends on things that will only be available in what will be iRODS 4.3.1.

**Comment by peggy0135** [comment]
OK, I see.
I will try it more
Thank you.

**Comment by trel** [comment]
Closing.
